### ISSUE TITLE
create data error

### ISSUE THREAD

**Issue by chinnikrishna55** [manutdzou/KITTI_SSD#5]
Traceback (most recent call last):
  File "/home/zc/caffe/data/VOC0712/../../scripts/create_annoset.py", line 103, in <module>
    label_map = caffe_pb2.LabelMap()
AttributeError: 'module' object has no attribute 'LabelMap'

 I am sure of python path and its importing caffe_pb2 correctly

**Comment by AgatheMead** [comment]
Hi, I have the same problem, when I tried this,
>>> import caffe
>>> from caffe.proto import caffe_pb2
>>> label_map=caffe_pb2.LabelMap()
>>> exit()

Have you figured it out?

**Comment by swearos** [comment]
@AgatheMead make sure you had make pycaffe,and add pycaffe  path to create_annoset.py

**Comment by AgatheMead** [comment]
@swearos Thanks! Before I ran create_annoset.py, I did: export PYTHONPATH='path/to/python' and it worked well!

**Comment by Samjith888** [comment]
Traceback (most recent call last):
  File "/home/sam/train_caffe/data/CustomDataset/../../scripts/create_annoset.py", line 103, in <module>
    label_map = caffe_pb2.LabelMap()
AttributeError: module 'caffe.proto.caffe_pb2' has no attribute 'LabelMap'
Traceback (most recent call last):
  File "/home/sam/train_caffe/data/CustomDataset/../../scripts/create_annoset.py", line 103, in <module>
    label_map = caffe_pb2.LabelMap()
AttributeError: module 'caffe.proto.caffe_pb2' has no attribute 'LabelMap'


I got this error
what do you meant by pycaffe path and at which line i have to add it?

**Comment by Samjith888** [comment]
@AgatheMead  @swearos
